# Generated by Django 4.2.1 on 2023-05-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_signup', '0003_user_created_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
