# Generated by Django 4.2.1 on 2023-05-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('base_experience', models.IntegerField()),
                ('height', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_default', models.BooleanField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('abilities', models.TextField(default='[]')),
                ('forms', models.TextField(default='[]')),
                ('game_indices', models.TextField(default='[]')),
                ('location_area_encounters', models.TextField(default='[]')),
                ('moves', models.TextField(default='[]')),
                ('past_types', models.TextField(default='[]')),
                ('species', models.TextField(default='[]')),
                ('sprites', models.TextField(default='[]')),
                ('stats', models.TextField(default='[]')),
                ('types', models.TextField(default='[]')),
            ],
        ),
    ]
