# Generated by Django 4.2.1 on 2023-05-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_abilities_alter_pokemon_forms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='game_indices',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='location_area_encounters',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='past_types',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='species',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sprites',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
    ]
